== What is OptaPlanner Simple Benchmark Daemon?

This is a simple and stupid benchmarking server that runs every benchmark config dropped into a directory.

It's implemented through a shell script that automatically runs every benchmark config dropped in the input dir and puts the results in the output dir.

== Usage

To start the server, run this command:

----
$ ./runInBackground.sh
----

Then drop your benchmark config in `local/input`
and wait until the results appear in `local/output`.

== Configuration

By default, you can only use OptaPlanner Examples in your benchmark config.
To use your own use case (by simply using the classpath of your own project instead of that of OptaPlanner Examples),
do this:

----
$ cp default.local.properties local.properties
$ gedit local.properties
----

== Directory structure

* `local/input`: Upload your `*BenchmarkConfig.xml` (or `*BenchmarkConfig.xml.ftl`) here.
* `local/ouput`: Download the benchmark reports here.

== Troubleshooting

If the `runInBackground.sh` command doesn't work, then run `./run.sh` instead to output information to the console.

== Developing Drools, OptaPlanner and jBPM

*If you want to build or contribute to a droolsjbpm project, https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/blob/master/README.md[read this document].*

*It will save you and us a lot of time by setting up your development environment correctly.*
It solves all known pitfalls that can disrupt your development.
It also describes all guidelines, tips and tricks.
If you want your pull requests (or patches) to be merged into master, please respect those guidelines.
